version: '3.8'

services:
  recura-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always

  recura-frontend:
    build:
      context: ./recura-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - recura-backend
    restart: always